import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const doctors = {
  Cardiology: 'Dr. Marcus Chen',
  Neurology: 'Dr. Sarah Jones',
  Orthopedics: 'Dr. Evelyn Reed',
  'General Medicine': 'Dr. Alex Thompson',
  Dermatology: 'Dr. Chloe Davis',
  ENT: 'Dr. Omar Khan',
  Gastroenterology: 'Dr. Lena Rodriguez',
  Physiotherapy: 'Dr. Ben Carter'
};

const starterRecords = [
  { id: 1, date: '2024-06-18', department: 'Cardiology', doctor: 'Dr. Marcus Chen', pain: 3, steps: 6820, sleep: 7.4, mood: 'Good', risk: 'Low', score: 24, note: 'Keep up the gentle daily walks and hydration.', recommendation: 'Maintain routine' },
  { id: 2, date: '2024-06-12', department: 'Cardiology', doctor: 'Dr. Marcus Chen', pain: 5, steps: 4910, sleep: 6.1, mood: 'Tired', risk: 'Moderate', score: 47, note: '', recommendation: 'Monitor closely' },
  { id: 3, date: '2024-05-29', department: 'Cardiology', doctor: 'Dr. Marcus Chen', pain: 6, steps: 3250, sleep: 5.8, mood: 'Stressed', risk: 'Moderate', score: 53, note: 'Please schedule a follow-up if fatigue continues.', recommendation: 'Monitor closely' }
];

function riskScore({ pain, steps, medicine, sleep, mood }) {
  const painScore = Math.min(Math.max(Number(pain || 0) / 10, 0), 1);
  const stepsScore = Number(steps) > 10000 ? .1 : Number(steps) > 6000 ? .3 : Number(steps) > 3000 ? .5 : .9;
  const medScore = medicine === 'Yes' ? .05 : .35;
  const sleepScore = Number(sleep) >= 7 ? .1 : Number(sleep) >= 5 ? .4 : .7;
  const moodScore = ['happy', 'energetic', 'relaxed', 'good'].includes(String(mood).toLowerCase()) ? .1 : ['sad', 'tired', 'stressed'].includes(String(mood).toLowerCase()) ? .6 : .3;
  const score = Math.round(Math.pow(.55 * painScore + .15 * stepsScore + .1 * medScore + .1 * sleepScore + .1 * moodScore, 1.4) * 100);
  return score >= 65 ? { risk: 'High', score, recommendation: 'Immediate consultation advised' } : score >= 40 ? { risk: 'Moderate', score, recommendation: 'Monitor closely' } : { risk: 'Low', score, recommendation: 'Maintain routine' };
}

const Icon = ({ name, size = 20 }) => {
  const paths = { grid: 'M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z', activity: 'M3 12h4l2-7 4 14 2-7h6', file: 'M6 3h8l4 4v14H6zM14 3v5h5M9 13h6M9 17h6', chat: 'M4 5h16v11H8l-4 4z', heart: 'M20.8 8.9c0 5.3-8.8 10.1-8.8 10.1S3.2 14.2 3.2 8.9A4.7 4.7 0 0 1 12 6.2a4.7 4.7 0 0 1 8.8 2.7Z', plus: 'M12 5v14M5 12h14', logout: 'M10 17l5-5-5-5M15 12H3M21 19V5a2 2 0 0 0-2-2h-5', doctor: 'M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm-7 9a7 7 0 0 1 14 0', bell: 'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4', arrow: 'M5 12h14m-6-6 6 6-6 6', check: 'm5 12 4 4L19 6' };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name] || paths.heart} /></svg>;
};

function App() {
  const [active, setActive] = useState('Overview');
  const [role, setRole] = useState('patient');
  const [records, setRecords] = useState(() => JSON.parse(localStorage.getItem('careflow-records') || 'null') || starterRecords);
  const [toast, setToast] = useState('');
  const [form, setForm] = useState({ department: 'Cardiology', pain: 4, steps: 6200, medicine: 'Yes', sleep: 7, mood: 'Good', notes: '' });
  const [question, setQuestion] = useState('');
  const [messages, setMessages] = useState([{ from: 'assistant', text: 'Hi Maya — I’m here to help you understand your health updates. What would you like to explore?' }]);

  const latest = records[0];
  const averagePain = Math.round(records.reduce((sum, item) => sum + item.pain, 0) / records.length * 10) / 10;
  const trend = useMemo(() => records.slice().reverse().map(item => item.pain), [records]);

  const notify = (message) => { setToast(message); window.setTimeout(() => setToast(''), 2800); };
  const submitReport = (event) => {
    event.preventDefault();
    const calculated = riskScore(form);
    const next = { id: Date.now(), date: new Date().toISOString().slice(0, 10), department: form.department, doctor: doctors[form.department], pain: Number(form.pain), steps: Number(form.steps), sleep: Number(form.sleep), mood: form.mood, ...calculated, note: '', notes: form.notes };
    const updated = [next, ...records];
    setRecords(updated); localStorage.setItem('careflow-records', JSON.stringify(updated));
    notify(`Report sent securely to ${doctors[form.department]}`); setActive('Records'); setForm({ ...form, notes: '' });
  };
  const askAssistant = (event) => {
    event.preventDefault();
    if (!question.trim()) return;
    const asked = question.trim();
    setMessages((items) => [...items, { from: 'user', text: asked }, { from: 'assistant', text: 'I can help you review patterns, but I can’t diagnose or prescribe. Your recent reports show an average pain level of ' + averagePain + '/10. If symptoms feel urgent or worsen, please contact your care team.' }]);
    setQuestion('');
  };

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark"><Icon name="heart" size={19} /></span><span>care<span>flow</span></span></div>
      <div className="profile"><div className="avatar">MS</div><div><strong>Maya Singh</strong><small>Patient account</small></div><button aria-label="Notifications" className="icon-button"><Icon name="bell" size={18} /></button></div>
      <nav><p className="nav-label">Workspace</p>{[['Overview','grid'],['New health update','plus'],['My records','file'],['AI assistant','chat']].map(([label, icon]) => <button key={label} className={active === label ? 'nav-item active' : 'nav-item'} onClick={() => setActive(label)}><Icon name={icon} size={18} />{label}</button>)}</nav>
      <div className="sidebar-bottom"><button className="role-switch" onClick={() => { setRole(role === 'patient' ? 'doctor' : 'patient'); setActive('Overview'); }}><span className="role-icon"><Icon name={role === 'patient' ? 'doctor' : 'heart'} size={16} /></span><span><small>Viewing as</small><strong>{role === 'patient' ? 'Patient portal' : 'Doctor dashboard'}</strong></span><Icon name="arrow" size={15} /></button><button className="nav-item logout"><Icon name="logout" size={18} />Sign out</button></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><div className="mobile-brand"><span className="brand-mark"><Icon name="heart" size={16} /></span>careflow</div><div className="breadcrumb">Workspace <span>/</span> {role === 'doctor' ? 'Doctor dashboard' : active}</div><div className="top-actions"><span className="status"><i /> All systems operational</span><button className="icon-button"><Icon name="bell" size={19} /></button><div className="mini-avatar">MS</div></div></header>
      {role === 'doctor' ? <DoctorDashboard records={records} notify={notify} /> : active === 'Overview' ? <Overview latest={latest} records={records} averagePain={averagePain} trend={trend} setActive={setActive} /> : active === 'New health update' ? <NewUpdate form={form} setForm={setForm} submitReport={submitReport} /> : active === 'My records' ? <Records records={records} /> : <Assistant messages={messages} question={question} setQuestion={setQuestion} askAssistant={askAssistant} />}
    </main>
    {toast && <div className="toast"><span className="toast-check"><Icon name="check" size={15} /></span>{toast}</div>}
  </div>;
}

function PageHeader({ eyebrow, title, copy, action }) { return <div className="page-header"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="page-copy">{copy}</p></div>{action}</div>; }
function Overview({ latest, records, averagePain, trend, setActive }) {
  const max = Math.max(...trend, 10);
  return <div className="page"><PageHeader eyebrow="Tuesday, June 18, 2024" title="Good morning, Maya" copy="Here’s a clear view of your health journey. Small steps add up." action={<button className="primary-button" onClick={() => setActive('New health update')}><Icon name="plus" size={17} /> New health update</button>} />
    <div className="metric-grid"><div className="metric-card highlight"><div className="metric-top"><span className="metric-icon"><Icon name="activity" /></span><span className="trend up">↑ 12% <small>vs. last month</small></span></div><strong>{latest.steps.toLocaleString()}</strong><span>Average daily steps</span><div className="sparkline">{[35,48,42,65,54,70,78].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div></div><div className="metric-card"><div className="metric-top"><span className="metric-icon green"><Icon name="heart" /></span><span className="trend up">↓ 0.8 <small>improving</small></span></div><strong>{averagePain}<em>/10</em></strong><span>Average pain level</span><div className="progress"><i style={{ width: `${averagePain * 10}%` }} /></div><small className="muted">Based on your last {records.length} updates</small></div><div className="metric-card"><div className="metric-top"><span className="metric-icon purple"><Icon name="check" /></span><span className="status-pill low">On track</span></div><strong>{latest.sleep}<em> hrs</em></strong><span>Average sleep</span><div className="sleep-bars">{[55,70,62,85,72,78,90].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div></div></div>
    <div className="content-grid"><section className="panel chart-panel"><div className="panel-heading"><div><h2>Health trends</h2><p>Reported pain levels over the last 30 days</p></div><button className="select-button">Last 30 days <span>⌄</span></button></div><div className="chart"><div className="y-axis"><span>10</span><span>7.5</span><span>5</span><span>2.5</span><span>0</span></div><div className="chart-area">{[0,2.5,5,7.5,10].map((_, i) => <div className="grid-line" style={{ top: `${i * 25}%` }} key={i} />)}<svg viewBox="0 0 600 190" preserveAspectRatio="none"><polyline points={trend.map((value, i) => `${i * (600 / (trend.length - 1))},${190 - value / 10 * 160 - 10}`).join(' ')} fill="none" stroke="#118b83" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />{trend.map((value, i) => <circle key={i} cx={i * (600 / (trend.length - 1))} cy={190 - value / 10 * 160 - 10} r="5" fill="#fff" stroke="#118b83" strokeWidth="3" />)}</svg><div className="x-axis"><span>May 29</span><span>Jun 5</span><span>Jun 12</span><span>Today</span></div></div></div></section><section className="panel next-panel"><div className="panel-heading"><div><h2>Next up</h2><p>Stay on top of your care</p></div><button className="more">•••</button></div><div className="appointment"><div className="date-box"><strong>24</strong><span>JUN</span></div><div><strong>Follow-up appointment</strong><p>Dr. Marcus Chen · 10:30 AM</p><span className="tag">Cardiology</span></div></div><div className="divider" /><div className="tip"><span><Icon name="heart" size={17} /></span><div><strong>Today’s wellness tip</strong><p>Try a 10-minute walk after lunch to support your energy levels.</p></div></div><button className="text-button" onClick={() => setActive('Records')}>View all activity <Icon name="arrow" size={16} /></button></section></div>
    <section className="panel recent-panel"><div className="panel-heading"><div><h2>Recent health updates</h2><p>Your latest reports and care team feedback</p></div><button className="text-button" onClick={() => setActive('Records')}>View all <Icon name="arrow" size={16} /></button></div><div className="table"><div className="table-row table-head"><span>Date</span><span>Department</span><span>Reported pain</span><span>Risk status</span><span>Care team note</span></div>{records.slice(0, 3).map(record => <div className="table-row" key={record.id}><span className="date-cell">{new Date(record.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</span><span>{record.department}<small>{record.doctor}</small></span><span><b className="pain-dot" /> {record.pain}/10</span><span><span className={`status-pill ${record.risk.toLowerCase()}`}><i /> {record.risk}</span></span><span className={record.note ? '' : 'muted'}>{record.note || 'Awaiting review'}</span></div>)}</div></section>
  </div>;
}
function NewUpdate({ form, setForm, submitReport }) { const update = (key, value) => setForm({ ...form, [key]: value }); return <div className="page narrow-page"><PageHeader eyebrow="Personal health" title="Share a health update" copy="Your update will be securely routed to the right care team member." /><form className="form-panel" onSubmit={submitReport}><div className="form-section"><div className="section-title"><span>01</span><div><h2>Care details</h2><p>Tell us where you’d like support today.</p></div></div><label>Department<select value={form.department} onChange={e => update('department', e.target.value)}>{Object.keys(doctors).map(item => <option key={item}>{item}</option>)}</select></label><div className="assigned"><span className="assigned-icon"><Icon name="doctor" size={18} /></span><div><small>Assigned care team member</small><strong>{doctors[form.department]}</strong></div><span className="verified">● Available</span></div></div><div className="form-section"><div className="section-title"><span>02</span><div><h2>How are you feeling?</h2><p>These details help us calculate a simple risk indicator — not a diagnosis.</p></div></div><div className="field-grid"><label>Pain level <div className="range-value">{form.pain}<small>/10</small></div><input type="range" min="0" max="10" value={form.pain} onChange={e => update('pain', e.target.value)} /><div className="range-labels"><span>No pain</span><span>Severe</span></div></label><label>Steps today <input type="number" min="0" value={form.steps} onChange={e => update('steps', e.target.value)} /><small className="input-help">Estimated steps walked</small></label><label>Sleep last night <div className="input-suffix"><input type="number" min="0" max="24" step=".1" value={form.sleep} onChange={e => update('sleep', e.target.value)} /><span>hours</span></div></label><label>Medicine taken? <select value={form.medicine} onChange={e => update('medicine', e.target.value)}><option>Yes</option><option>No</option></select></label></div><label>Mood <div className="choice-grid">{['Good', 'Neutral', 'Tired', 'Stressed'].map(item => <button type="button" className={form.mood === item ? 'choice selected' : 'choice'} key={item} onClick={() => update('mood', item)}>{item}</button>)}</div></label><label>Anything else you’d like your care team to know? <textarea placeholder="Share symptoms, questions, or context..." value={form.notes} onChange={e => update('notes', e.target.value)} /></label></div><div className="form-footer"><span><Icon name="heart" size={16} /> Your information is private and encrypted</span><button className="primary-button" type="submit">Submit health update <Icon name="arrow" size={17} /></button></div></form></div>; }
function Records({ records }) { return <div className="page"><PageHeader eyebrow="Your care history" title="My records" copy="A timeline of your health updates, risk indicators, and care team feedback." action={<button className="secondary-button"><Icon name="file" size={17} /> Download summary</button>} /><div className="record-list">{records.map(record => <article className="record-card" key={record.id}><div className="record-date"><strong>{new Date(record.date).toLocaleDateString('en-US', { day: '2-digit' })}</strong><span>{new Date(record.date).toLocaleDateString('en-US', { month: 'short' })}</span></div><div className="record-main"><div className="record-heading"><div><h2>{record.department} update</h2><p>{record.doctor} · {new Date(record.date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p></div><span className={`status-pill ${record.risk.toLowerCase()}`}><i /> {record.risk} risk · {record.score}</span></div><div className="record-stats"><span><small>Pain</small><strong>{record.pain}/10</strong></span><span><small>Steps</small><strong>{record.steps.toLocaleString()}</strong></span><span><small>Sleep</small><strong>{record.sleep} hrs</strong></span><span><small>Mood</small><strong>{record.mood}</strong></span></div><div className={record.note ? 'care-note' : 'care-note empty'}><Icon name="doctor" size={17} /><span><strong>{record.note ? 'Care team note' : 'Awaiting care team review'}</strong>{record.note || 'Your care team will add feedback here.'}</span></div></div></article>)}</div></div>; }
function Assistant({ messages, question, setQuestion, askAssistant }) { return <div className="page assistant-page"><PageHeader eyebrow="Private support" title="AI health assistant" copy="A thoughtful place to reflect on your updates. This assistant does not diagnose or prescribe." /><div className="assistant-layout"><div className="assistant-card"><div className="assistant-intro"><span className="assistant-logo"><Icon name="heart" size={25} /></span><div><h2>Careflow companion</h2><p>Grounded in your recent health updates</p></div><span className="online"><i /> Online</span></div><div className="messages">{messages.map((message, index) => <div className={`message ${message.from}`} key={index}><span className="message-avatar">{message.from === 'assistant' ? <Icon name="heart" size={14} /> : 'MS'}</span><div>{message.text}</div></div>)}</div><form className="chat-input" onSubmit={askAssistant}><input value={question} onChange={e => setQuestion(e.target.value)} placeholder="Ask about your recent health updates..." /><button aria-label="Send message"><Icon name="arrow" size={18} /></button></form></div><aside className="safety-card"><span className="safety-icon"><Icon name="heart" size={18} /></span><h3>A note on safety</h3><p>This assistant offers general information based on what you share. It is not a medical professional and cannot replace advice from your care team.</p><button className="text-button">Learn more <Icon name="arrow" size={15} /></button></aside></div></div>; }
function DoctorDashboard({ records, notify }) { const queue = records.slice().sort((a, b) => b.score - a.score); return <div className="page"><PageHeader eyebrow="Clinical workspace" title="Good morning, Dr. Chen" copy="Three patient updates need your review today." action={<button className="primary-button" onClick={() => notify('Patient queue refreshed')}><Icon name="activity" size={17} /> Refresh queue</button>} /><div className="metric-grid doctor-metrics"><div className="metric-card"><span className="metric-icon red"><Icon name="heart" /></span><strong>{queue.filter(item => item.risk === 'High').length}</strong><span>High-risk updates</span></div><div className="metric-card"><span className="metric-icon amber"><Icon name="activity" /></span><strong>{queue.filter(item => item.risk === 'Moderate').length}</strong><span>Moderate-risk updates</span></div><div className="metric-card"><span className="metric-icon green"><Icon name="check" /></span><strong>{queue.filter(item => item.risk === 'Low').length}</strong><span>Low-risk updates</span></div></div><section className="panel queue-panel"><div className="panel-heading"><div><h2>Patient review queue</h2><p>Prioritized by risk score and most recent submission</p></div><button className="select-button">All patients <span>⌄</span></button></div>{queue.map(item => <div className="queue-row" key={item.id}><div className="avatar patient-avatar">{item.department.slice(0, 2)}</div><div className="queue-patient"><strong>Maya Singh</strong><small>{item.department} · Submitted {item.date}</small></div><span className={`status-pill ${item.risk.toLowerCase()}`}><i /> {item.risk} · {item.score}</span><p>{item.recommendation}</p><button className="secondary-button small" onClick={() => notify('Note editor ready for Maya Singh')}>Review update <Icon name="arrow" size={15} /></button></div>)}</section></div>; }

createRoot(document.getElementById('root')).render(<App />);
